name: Agent-Bot

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, ready_for_review, synchronize]

permissions: write-all

jobs:
  run:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/agent'))

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: ↓ Base64 文字列 → bot.py に復号
        env:
          BOT_B64: ${{ secrets.BOT_CODE_B64 }}
        run: |
          echo "$BOT_B64" | base64 -d > bot.py
          chmod +x bot.py

      - name: Execute Agent bot script
        env:
          CLAUDE_ACCESS_TOKEN:  ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          CLAUDE_REFRESH_TOKEN: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          CLAUDE_EXPIRES_AT:    ${{ secrets.CLAUDE_EXPIRES_AT }}
          DISCORD_WEBHOOK_URL:  ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_EVENT_PATH:    ${{ github.event_path }}
          GITHUB_WORKSPACE:     ${{ github.workspace }}
        run: |
          python tools/issue_coder.py
